services:
  - type: web
    name: ecommerce-backend
    env: php
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /tmp/database.sqlite
      - key: LOG_CHANNEL
        value: stderr